version: '3'
services:
  postgres:
    ports:
      - '5433:5432'
    container_name: container-postgresql
    environment:
      - POSTGRES_PASSWORD=mypass
    volumes:
      - 'container-postgresql-volume:/var/lib/postgresql/data'
    image: 'postgres:10.4'
    networks:
      - container-network
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
    networks:
      - container-network
volumes:
  container-postgresql-volume:
  mongodata:
networks:
  container-network:
    driver: bridge