version: '3'
services:
  postgres:
    container_name: container-postgresql
    image: 'postgres:10.4'
    environment:
      - POSTGRES_PASSWORD=mypass
    volumes:
      - 'container-postgresql-volume:/var/lib/postgresql/data'
    networks:
      - mynetwork  # Connect this service to the custom network

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    volumes:
      - mongodata:/var/lib/mongodb/data
    networks:
      - mynetwork  # Connect this service to the custom network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - mynetwork  # Connect this service to the custom network

  auction-svc:
    image: sabuha/auction-svc:latest
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq  # Use the service name as the hostname
      - ConnectionString__DefaultConnection=Server=postgres;Port=5432;User Id=postgres;Password=mypass;Database=auctions
      - IdentityServiceUrl=http://identity-svc
    ports:
      - 7001:80
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - mynetwork  # Connect this service to the custom network

  search-svc:
    image: sabuha/search-svc:latest
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq  # Use the service name as the hostname
      - ConnectionString__MongoDbConnection=mongodb://root:mongopw@mongodb  # Use the service name as the hostname
      - AuctionServiceUrl=http://auction-svc
    ports:
      - 7002:80
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - mynetwork  # Connect this service to the custom network

volumes:
  container-postgresql-volume:
  mongodata:

networks:
  mynetwork:  # Define a custom network for your services
    driver: bridge
